### ISSUE TITLE
error creating project

### ISSUE THREAD

**Issue by davidmoshal** [tinesoft/nxrocks#15]
Plugin Version:
- 1.1.0

Nx Version (`nx --version`):
- 11.0.16

Angular CLI version (`ng --version`):
- not using angular

#### Expected Behaviour
expected the command:   
` nx g @nxrocks/nx-spring-boot:app `   
to create a spring application.

#### Actual Behaviour
```sh
TypeError: Cannot read property 'toString' of null
`

#### Steps to reproduce the behaviour
```sh
nx g @nxrocks/nx-spring-boot:app       
? What name would you like to use? spring
? Which type of project would you like to generate? Gradle Project
? Which packaging would you like to use? Jar
? Which version of Java would you like to use? 11
? Which language would you like to use? Kotlin
? What groupId would you like to use? com.au11s
? What artifactId would you like to use? spring
? What package name would you like to use? com.au11s.spring
? What is the project about? experiments
? What dependencies would you like to use (comma separated)?
        > Go to https://start.spring.io/dependencies to get the ids needed here 
    Downloading Spring Boot project zip from : https://start.spring.io/starter.zip?type=gradle-project&language=kotlin&groupdId=com.au11s&artifactId=spring&packageName=com.au11s.spring&javaVersion=11&packaging=jar&description=experiments...
    Extracting Spring Boot project zip to : apps/spring...
TypeError: Cannot read property 'toString' of null
    at /home/davem/au/codebase/2020/au-2020-devops-api/node_modules/@nxrocks/nx-spring-boot/src/schematics/application/lib/add-build-info-task.js:13:51
    at MergeMapSubscriber.project (/home/davem/au/codebase/2020/au-2020-devops-api/node_modules/@angular-devkit/schematics/src/rules/call.js:75:24)
    at MergeMapSubscriber._tryNext (/home/davem/au/codebase/2020/au-2020-devops-api/node_modules/rxjs/internal/operators/mergeMap.js:67:27)
    at MergeMapSubscriber._next (/home/davem/au/codebase/2020/au-2020-devops-api/node_modules/rxjs/internal/operators/mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (/home/davem/au/codebase/2020/au-2020-devops-api/node_modules/rxjs/internal/Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (/home/davem/au/codebase/2020/au-2020-devops-api/node_modules/rxjs/internal/operators/mergeMap.js:93:26)
    at SimpleInnerSubscriber._next (/home/davem/au/codebase/2020/au-2020-devops-api/node_modules/rxjs/internal/innerSubscribe.js:27:21)
    at SimpleInnerSubscriber.Subscriber.next (/home/davem/au/codebase/2020/au-2020-devops-api/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Observable._subscribe (/home/davem/au/codebase/2020/au-2020-devops-api/node_modules/rxjs/internal/util/subscribeToArray.js:5:20)
    at Observable._trySubscribe (/home/davem/au/codebase/2020/au-2020-devops-api/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/home/davem/au/codebase/2020/au-2020-devops-api/node_modules/rxjs/internal/Observable.js:30:22)
    at Object.innerSubscribe (/home/davem/au/codebase/2020/au-2020-devops-api/node_modules/rxjs/internal/innerSubscribe.js:102:23)
    at MergeMapSubscriber._innerSub (/home/davem/au/codebase/2020/au-2020-devops-api/node_modules/rxjs/internal/operators/mergeMap.js:80:50)
    at MergeMapSubscriber._tryNext (/home/davem/au/codebase/2020/au-2020-devops-api/node_modules/rxjs/internal/operators/mergeMap.js:74:14)
    at MergeMapSubscriber._next (/home/davem/au/codebase/2020/au-2020-devops-api/node_modules/rxjs/internal/operators/mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (/home/davem/au/codebase/2020/au-2020-devops-api/node_modules/rxjs/internal/Subscriber.js:66:18)
Cannot read property 'toString' of null
```

**Comment by davidmoshal** [comment]
Note: it seems that this error is specific to Kotlin Gradle projects only!
- Gradle/Kotlin project creation fails.
- Gradle/Java project creation works.
- Maven/Kotlin project creation works.
David

**Comment by davidmoshal** [comment]
Workaround:
1) create a Gradle/Java project say "projectJ".
2) create a Gradle/Kotlin project say "projectK".
- Even though projectK fails with above error message, the Spring project is created (though nx.json and workspace.json are not updated).
3) manually copy and paste the "projectK" information in nx.json and workspace.json, renaming projectJ references to projectK.
4) remove ProjectJ (nx g remove projectJ).

**Comment by tinesoft** [comment]
Hi @davidmoshal 

Thanks for using the plugin, and for reporting the issue, as well as the workaround.

I will look into it and provide a proper fix asap.


Cheers!
