### ISSUE TITLE
[Bug] TypeError: Cannot read properties of undefined (reading 'filter')

### ISSUE THREAD

**Issue by nathan2slime** [tinesoft/nxrocks#166]
### Plugin Name

@nxrocks/nx-flutter

### Plugin Version

6.0.0

### Nx Version

15.8.0

### Expected Behaviour

Should generate a shareable Flutter project containing modular Dart code

### Actual Behaviour

```
D:\Projects\goland\node_modules\enquirer\lib\types\array.js:509
    let result = choices.filter(fn);
                         ^

TypeError: Cannot read properties of undefined (reading 'filter')
    at MultiSelect.filter (D:\Projects\goland\node_modules\enquirer\lib\types\array.js:509:26)
    at get enabled [as enabled] (D:\Projects\goland\node_modules\enquirer\lib\types\array.js:620:17)
    at get selected [as selected] (D:\Projects\goland\node_modules\enquirer\lib\types\array.js:636:33)
    at MultiSelect.submit (D:\Projects\goland\node_modules\enquirer\lib\types\array.js:546:22)
    at D:\Projects\goland\node_modules\enquirer\lib\prompt.js:234:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.16.0
```

![Captura de tela 2023-04-28 222511](https://user-images.githubusercontent.com/105957472/235276981-c2436e1c-a8d0-423e-9ffc-0abd89620cb8.png)

### Steps to reproduce the behaviour

1. Run the command to generate a shareable Flutter project containing modular Dart code 
![Captura de tela 2023-04-28 222511](https://user-images.githubusercontent.com/105957472/235277104-ef353287-c673-4609-bf5b-68aa4f8f7ed1.png)

**Comment by nathan2slime** [comment]
Thank you, solved 👌
