### ISSUE TITLE
[Bug] Cannot run any nx command after creating micronaut project

### ISSUE THREAD

**Issue by adworzynski** [tinesoft/nxrocks#217]
### Plugin Name

@nxrocks/nx-micronaut

### Nx Report

Error:
 >  NX   Failed to process project dependencies with "@nxrocks/nx-micronaut".

   Cannot read properties of undefined (reading 'dependencies')

### Expected Behaviour

Command should run

### Actual Behaviour

Error:

>  NX   Failed to process project dependencies with "@nxrocks/nx-micronaut".

   Cannot read properties of undefined (reading 'dependencies')

### Steps to reproduce the behaviour

1. npm install @nxrocks/nx-micronaut --save-dev
2. nx g @nxrocks/nx-micronaut:project project-name
3. nx run -t test -p project-name

**Comment by peterhnm** [comment]
I have the same problem with `@nxrocks/nx-spring-boot` when trying to create a new node app `nx g @nx/node:application my-new-app`

```
@nx@18.1.3
@nxrocks/nx-spring-boot@10.0.0
```

Here is the complete error message:
```
TypeError: Failed to process project dependencies with "@nxrocks/nx-spring-boot".
Cannot read properties of undefined (reading 'dependencies')
    at getDependenciesForProject (~/Projects/miranum/miranum-ide/node_modules/@nxrocks/common/src/lib/workspace/project-graph.js:38:25)
    at createDependenciesIf (~/Projects/miranum/miranum-ide/node_modules/@nxrocks/common/src/lib/workspace/project-graph.js:119:52)
    at Object.createDependencies (~/Projects/miranum/miranum-ide/node_modules/@nxrocks/nx-spring-boot/src/graph/create-dependencies.js:7:78)
    at ~/Projects/miranum/miranum-ide/node_modules/nx/src/project-graph/build-project-graph.js:189:47
    at Array.map ()
    at updateProjectGraphWithPlugins (~/Projects/miranum/miranum-ide/node_modules/nx/src/project-graph/build-project-graph.js:186:47)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async buildProjectGraphUsingContext (~/Projects/miranum/miranum-ide/node_modules/nx/src/project-graph/build-project-graph.js:104:15)
    at async buildProjectGraphUsingProjectFileMap (~/Projects/miranum/miranum-ide/node_modules/nx/src/project-graph/build-project-graph.js:68:24)
    at async createAndSerializeProjectGraph (~/Projects/miranum/miranum-ide/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:179:55)
    at async getCachedSerializedProjectGraphPromise (~/Projects/miranum/miranum-ide/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:43:16)
    at async handleRequestProjectGraph (~/Projects/miranum/miranum-ide/node_modules/nx/src/daemon/server/handle-request-project-graph.js:12:24)
    at async handleResult (~/Projects/miranum/miranum-ide/node_modules/nx/src/daemon/server/server.js:110:16)
    at async handleMessage (~/Projects/miranum/miranum-ide/node_modules/nx/src/daemon/server/server.js:81:9)
    at async ~/Projects/miranum/miranum-ide/node_modules/nx/src/daemon/server/server.js:45:9
```

I hope this helps a little bit 😃.

**Comment by tinesoft** [comment]
Thanks for using the plugin and for reporting this...
I didn't show on my e2e test, nor nightly builds...

Having a look right now

**Comment by tinesoft** [comment]
I just did the following:

```

npx --yes create-nx-workspace@latest nx18 // to create the workspace

npx nx add @nxrocks/nx-spring-boot@latest //to add the plugin

npx nx g @nxrocks/nx-spring-boot:project bootapp //to create the project

npx nx  graph
```
No Error, and the dependencies graph is shown properly...

But after adding another plugin (nx-micronaut) I do see the error...

Can you run `nx report` and share the output please?

Also can you tell me if your workspace contains other  Maven or Gradle projects ?

**Comment by peterhnm** [comment]
Hello @tinesoft,

thanks for the reply.
I still get the error.
Running `nx report` gives me the same error as described above.
My workspace contains only node/web applications stored in `apps/` and one multi-module spring boot application stored in `spring-boot-apps/`

**Comment by tinesoft** [comment]
Hi @peterhnm 

Thanks for your input.

I believe I have fixed the issue (yet to be released).

Can you share the file structure of your workspace, in particular your multi-module spring boot apps  ?

I want to make sure the fix will work well in your case

**Comment by peterhnm** [comment]
Ah, sorry my mistake I thought it was released.

My workspace looks as follows:

```
.
├── .nx
├── apps
│   ├── node-app_1
│   │   ├── src
│   │   └── project.json
│   ├── node-app_2
│   │   ├── src
│   │   └── project.json
│   └── node-app_3
│       ├── src
│       └── project.json
├── libs
├── nx.json
├── package-lock.json
├── package.json
├── spring-boot-apps
│   └── parent-module
│       ├── .mvn
│       ├── local.env
│       ├── child-module_1
│       │   └── pom.xml
│       ├── child-module_2
│       │   ├── pom.xml
│       │   └── src
│       ├── child-module_3
│       │   ├── pom.xml
│       │   └── src
│       ├── mvnw
│       ├── mvnw.cmd
│       ├── pom.xml
│       └── project.json
└── tsconfig.base.json
```

**Comment by tinesoft** [comment]
Ok thanks!

I will make sure the fix works with that setup. If ok, expect a release soonish (today)

**Comment by tinesoft** [comment]
Tested and found no more issue.

You can update to `latest` published version of the plugins

**Comment by peterhnm** [comment]
Yes it works 🚀. Thank you very much.
