### ISSUE TITLE
[Bug] Spring boot multi-modules project doesn't work

### ISSUE THREAD

**Issue by pierrickrouxel** [tinesoft/nxrocks#223]
### Plugin Name

@nxrocks/nx-spring-boot

### Nx Report

I can't produce the nx report because the command doesn't work.

```sh
npx create-nx-spring-boot@latest
┌  create-nx-spring-boot
│
◇  What is the name of your workspace (e.g. org name)?
│  myorg
│
◇  Would you like to use Nx Wrapper? [ https://nx.dev/concepts/more-concepts/nx-and-the-wrapper#and-the-nx-wrapper ]
│  Yes
│
◇  Would you like Nx Cloud to make your CI faster? [ https://nx.app/?utm_source=create-nx-spring-boot ]
│  Skip for now
│

added 59 packages, and audited 171 packages in 582ms

22 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

 NX  Generating @nxrocks/nx-spring-boot:preset

✔ What is the name of your project? · unity
✔ What kind of project are you generating? · application
✔ Which build system would you like to use? · gradle-project-kotlin
✔ Which packaging would you like to use? · jar
✔ Which version of Java would you like to use? · 21
✔ Which language would you like to use? · java
✔ What groupId would you like to use? · com.example
✔ What artifactId would you like to use? · demo
✔ What package name would you like to use? · com.example.demo
⏳ Fetching Spring Boot dependencies list. Please wait...
? What dependencies would you like to use? (type something to filter, press [space] to multi-select) … 
✔ What dependencies would you like to use? (type something to filter, press [space] to multi-select) · web
⏳ Checking for existing multi-module projects. Please wait...
✔ Would you like to transform the generated project into a Gradle multi-module project? (y/N) · true
✔ What name would you like to use for the Gradle multi-module project? · unity-parent
✔ A root Gradle wrapper will be added in the root module 'unity-parent'. Do you want to keep the one in the generated child module 'unity'? (y/N) · false
⚙️ Generating project configuration...
⬇️ Downloading Spring Boot project zip from : https://start.spring.io/starter.zip?type=gradle-project-kotlin&language=java&name=unity&groupId=com.example&artifactId=demo&packageName=com.example.demo&javaVersion=21&packaging=jar&dependencies=web...
📦 Extracting Spring Boot project zip to '/Users/pierrickrouxel/Projects/monorepo/myorg/unity-parent/unity'...
Adding 'buildInfo' task to the build.gradle.kts file...
Adding 'maven-publish' plugin...
CREATE unity-parent/settings.gradle.kts
CREATE unity-parent/build.gradle.kts
CREATE unity-parent/project.json
CREATE unity-parent/unity/project.json
CREATE unity-parent/gradlew
CREATE unity-parent/unity/HELP.md
CREATE unity-parent/unity/.gitignore
CREATE unity-parent/unity/settings.gradle.kts
CREATE unity-parent/unity/build.gradle.kts
CREATE unity-parent/unity/src/test/java/com/example/demo/UnityApplicationTests.java
CREATE unity-parent/unity/src/main/java/com/example/demo/UnityApplication.java
CREATE unity-parent/unity/src/main/resources/application.properties
CREATE unity-parent/gradlew.bat
CREATE unity-parent/gradle/wrapper/gradle-wrapper.properties
CREATE unity-parent/gradle/wrapper/gradle-wrapper.jar
UPDATE nx.json
◇  Successfully created the workspace: myorg
│
◇  Next steps ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                       │
│  - Go to [ https://github.com/tinesoft/nxrocks/tree/develop/packages/nx-spring-boot ] to get started with Nx and Spring Boot plugin.  │
│  - Run   [ ./nx g @nxrocks/nx-spring-boot:project ] to add more projects.                                                             │
│  - Go to [ https://nx.dev/concepts/more-concepts/nx-and-the-wrapper#and-the-nx-wrapper ] to get started with Nx Wrapper.              │
│  - Go to [ https://nx.dev ] to get started with Nx.                                                                                   │
│                                                                                                                                       │
├───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
│
└  Your workspace in /Users/pierrickrouxel/Projects/monorepo/myorg is all set 🎉. Let's goooooo! 🚀

 ~/Projects/monorepo  cd myorg 
 ~/Projects/monorepo/myorg  nx graph

 NX   Failed to process project graph.

Pass --verbose to see the stacktraces.
```

With stacktrace:

```sh
nx --verbose report

 NX   Failed to process project graph. See errors below.

Failed to process project graph.
  The "@nxrocks/nx-spring-boot" plugin threw an error while creating nodes from unity-parent/build.gradle.kts:
    TypeError: Cannot read properties of undefined (reading 'applied')
        at getProjectTypeAndTargetsFromFile (/Users/pierrickrouxel/Projects/monorepo/myorg/.nx/installation/node_modules/@nxrocks/nx-spring-boot/src/utils/plugin-utils.js:28:90)
        at /Users/pierrickrouxel/Projects/monorepo/myorg/.nx/installation/node_modules/@nxrocks/common/src/lib/workspace/project-graph.js:101:23
        at createProjectConfigurations (/Users/pierrickrouxel/Projects/monorepo/myorg/.nx/installation/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:251:25)
        at _retrieveProjectConfigurations (/Users/pierrickrouxel/Projects/monorepo/myorg/.nx/installation/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:61:74)
        at retrieveProjectConfigurations (/Users/pierrickrouxel/Projects/monorepo/myorg/.nx/installation/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:46:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async processFilesAndCreateAndSerializeProjectGraph (/Users/pierrickrouxel/Projects/monorepo/myorg/.nx/installation/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:148:26)
        at async getCachedSerializedProjectGraphPromise (/Users/pierrickrouxel/Projects/monorepo/myorg/.nx/installation/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:45:16)
        at async handleRequestProjectGraph (/Users/pierrickrouxel/Projects/monorepo/myorg/.nx/installation/node_modules/nx/src/daemon/server/handle-request-project-graph.js:12:24)
        at async handleResult (/Users/pierrickrouxel/Projects/monorepo/myorg/.nx/installation/node_modules/nx/src/daemon/server/server.js:110:16)
        at async handleMessage (/Users/pierrickrouxel/Projects/monorepo/myorg/.nx/installation/node_modules/nx/src/daemon/server/server.js:81:9)
        at async /Users/pierrickrouxel/Projects/monorepo/myorg/.nx/installation/node_modules/nx/src/daemon/server/server.js:45:9
The "@nxrocks/nx-spring-boot" plugin threw an error while creating nodes from unity-parent/settings.gradle.kts:
    TypeError: Cannot read properties of undefined (reading 'applied')
        at getProjectTypeAndTargetsFromFile (/Users/pierrickrouxel/Projects/monorepo/myorg/.nx/installation/node_modules/@nxrocks/nx-spring-boot/src/utils/plugin-utils.js:28:90)
        at /Users/pierrickrouxel/Projects/monorepo/myorg/.nx/installation/node_modules/@nxrocks/common/src/lib/workspace/project-graph.js:101:23
        at createProjectConfigurations (/Users/pierrickrouxel/Projects/monorepo/myorg/.nx/installation/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:251:25)
        at _retrieveProjectConfigurations (/Users/pierrickrouxel/Projects/monorepo/myorg/.nx/installation/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:61:74)
        at retrieveProjectConfigurations (/Users/pierrickrouxel/Projects/monorepo/myorg/.nx/installation/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:46:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async processFilesAndCreateAndSerializeProjectGraph (/Users/pierrickrouxel/Projects/monorepo/myorg/.nx/installation/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:148:26)
        at async getCachedSerializedProjectGraphPromise (/Users/pierrickrouxel/Projects/monorepo/myorg/.nx/installation/node_modules/nx/src/daemon/server/project-graph-incremental-recomputation.js:45:16)
        at async handleRequestProjectGraph (/Users/pierrickrouxel/Projects/monorepo/myorg/.nx/installation/node_modules/nx/src/daemon/server/handle-request-project-graph.js:12:24)
        at async handleResult (/Users/pierrickrouxel/Projects/monorepo/myorg/.nx/installation/node_modules/nx/src/daemon/server/server.js:110:16)
        at async handleMessage (/Users/pierrickrouxel/Projects/monorepo/myorg/.nx/installation/node_modules/nx/src/daemon/server/server.js:81:9)
        at async /Users/pierrickrouxel/Projects/monorepo/myorg/.nx/installation/node_modules/nx/src/daemon/server/server.js:45:9
```

### Expected Behaviour

The CLI should works normally.

### Actual Behaviour

All commands fails with the same exception:

```
Cannot read properties of undefined (reading 'applied')
```

### Steps to reproduce the behaviour

1. Create a workspace using: `npx create-nx-spring-boot@latest`
2. Answer yes to the question: `Would you like to transform the generated project into a Gradle multi-module project? (y/N)`

I tried with and without the `integrated monorepo`, the problem appears always when the project is multi-module.

**Comment by tinesoft** [comment]
Hi @pierrickrouxel 

Thanks for using the plugin and for reporting this. 

I will have a look shortly and keep you posted.

Cheers

**Comment by pierrickrouxel** [comment]
Hi, thank you very much.
I'm currently on a Gradle monorepo hosting a Java / Typescript projects.
Your plugin sounds very good to our needs.

**Comment by tinesoft** [comment]
I'm glad to hear that 😊

I will do my best to fix the issue asap!


Don't hesitate to star ⭐ the project on Github, if you like it ^^

**Comment by tinesoft** [comment]
Hi @pierrickrouxel 

I identified and fixed the main issue you  found above.

While fixing it, I discovered another issue when building the project graph for Gradle-based projects.

I'll include both fixes and release soon (hopefully tonight or tomorrow).

Stay tuned!

**Comment by tinesoft** [comment]
Hi. 

Latest version of the plugin:

https://github.com/tinesoft/nxrocks/releases/tag/nx-spring-boot%2Fv10.0.2

 should fix your issue. Can you try again and let me know?

**Comment by pierrickrouxel** [comment]
Hello, it works ! Thank you very much !

**Comment by pierrickrouxel** [comment]
@tinesoft
> While fixing it, I discovered another issue when building the project graph for Gradle-based projects.

Did you fix this issue? I run an integrated monorepo with a multi-module project. The links between modules aren't defined in the graph.

**Comment by tinesoft** [comment]
Hi,

Yes it was fixed during my testing, that why I took so long to  release it.


Can you share the `build.gradle` and `settings.gradle`  files in the parent module folder, along with the ones in the children modules please?

How did you define the dependencies between the modules?

**Comment by tinesoft** [comment]
Hi @pierrickrouxel 

Thanks for letting me know. There was indeed a [slight change](https://github.com/tinesoft/nxrocks/commit/571424a7097daaa430ce469264e05a6b16f1e142) required for `Gradle` project using `Kotlin DSL`.
I will release it soonish
