### ISSUE TITLE
[Bug] Unable to create new Spring Boot application with the latest version of NX

### ISSUE THREAD

**Issue by Divaaaaaan** [tinesoft/nxrocks#238]
### Plugin Name

@nxrocks/nx-spring-boot

### Nx Report

```~/Workspace/Work/Bedrock git:[main] bunx nx report

 NX   Report complete - copy this into the issue template

Node           : 20.18.0
OS             : linux-x64
Native Target  : x86_64-linux
bun            : 1.1.30

nx             : 20.0.0
@nx/js         : 20.0.0
@nx/eslint     : 20.0.0
@nx/workspace  : 20.0.0
@nx/angular    : 20.0.0
@nx/devkit     : 20.0.0
@nx/vite       : 20.0.0
@nx/web        : 20.0.0
@nx/webpack    : 20.0.0
typescript     : 5.6.3
---------------------------------------
Community plugins:
@analogjs/content             : 1.8.2
@analogjs/platform            : 1.8.2
@analogjs/router              : 1.8.2
@analogjs/vite-plugin-angular : 1.8.2
@nxrocks/nx-spring-boot       : 10.2.6

### Expected Behaviour

Create a project using `nx g @nxrocks/nx-spring-boot:project`.

### Actual Behaviour

```~/Workspace/Work/Bedrock git:[main] bunx nx g @nxrocks/nx-spring-boot:project test --verbose

 NX  Generating @nxrocks/nx-spring-boot:project

✔ What kind of project are you generating? · application
✔ Which build system would you like to use? · maven-project
✔ Which packaging would you like to use? · jar
✔ Which version of Java would you like to use? · 22
✔ Which language would you like to use? · java
✔ What groupId would you like to use? · com.test
✔ What artifactId would you like to use? · test
✔ What package name would you like to use? · com.test.api

 NX   Cannot read properties of undefined (reading 'replace')

TypeError: Cannot read properties of undefined (reading 'replace')
    at removeWindowsDriveLetter (/home/user/Workspace/Work/Bedrock/node_modules/nx/src/utils/path.js:9:27)
    at normalizePath (/home/user/Workspace/Work/Bedrock/node_modules/nx/src/utils/path.js:16:12)
    at determineProjectNameAndRootOptions (/home/user/Workspace/Work/Bedrock/node_modules/@nx/devkit/src/generators/project-name-and-root-utils.js:10:58)
    at normalizeOptions (/home/user/Workspace/Work/Bedrock/node_modules/@nxrocks/nx-spring-boot/src/generators/project/lib/normalize-options.js:6:144)
    at projectGenerator (/home/user/Workspace/Work/Bedrock/node_modules/@nxrocks/nx-spring-boot/src/generators/project/generator.js:9:64)
    at /home/user/Workspace/Work/Bedrock/node_modules/nx/src/command-line/generate/generate.js:238:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleErrors (/home/user/Workspace/Work/Bedrock/node_modules/nx/src/utils/handle-errors.js:9:24)
    at async Object.handler (/home/user/Workspace/Work/Bedrock/node_modules/nx/src/command-line/generate/command-object.js:14:22)

### Steps to reproduce the behaviour

1. Create new nx workspace with "none" preset
2. Install @nxrocks/nx-spring-boot
3. Try and create a spring boot application

**Comment by Divaaaaaan** [comment]
It seems like the directory is null when logging out the options in `normalize-options.js`

**Comment by tinesoft** [comment]
Hi @Divaaaaaan 

Thanks for reporting this, I'll have a look and provide an update soonish.


Stay tuned!

**Comment by Divaaaaaan** [comment]
@tinesoft Just an update, seems like things are not playing well together when I edited the file :sweat_smile: so will wait for the update rather before continuing.

**Comment by WodenWang820118** [comment]
Having a look at the [Nx plugin registry](https://nx.dev/plugin-registry), it supports the Nx version between 16 and 18. When will the plugin be updated accordingly?

**Comment by lordvins226** [comment]
Hi @Divaaaaaan. 

"In Nx 20, generating projects will no longer derive the name and root"

So the correct way to create projects now is:
nx g @nxrocks/nx-spring-boot:project testapp --directory testapp

This same change affects both Spring Boot and Flutter projects in Nx 20.
![CleanShot 2024-10-28 at 4  18 22@2x](https://github.com/user-attachments/assets/5a14f180-0d1b-4ad0-a35f-d88fdec0afaf)

**Comment by crafael23** [comment]
> Hi @Divaaaaaan.
> 
> "In Nx 20, generating projects will no longer derive the name and root"
> 
> So the correct way to create projects now is: `nx g @nxrocks/nx-spring-boot:project testapp --directory apps/testapp ` This same change affects both Spring Boot and Flutter projects in Nx 20. ![CleanShot 2024-10-28 at 4  18 22@2x](https://private-user-images.githubusercontent.com/39868202/380798388-5a14f180-0d1b-4ad0-a35f-d88fdec0afaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzODQ4ODUsIm5iZiI6MTczMTM4NDU4NSwicGF0aCI6Ii8zOTg2ODIwMi8zODA3OTgzODgtNWExNGYxODAtMGQxYi00YWQwLWEzNWYtZDg4ZmRlYzBhZmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA0MDk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNTM3YzQ0YzkxMTAyN2MyYzc1MjRhZGYwZWVjZTlmMzA1ZTY4ODA1M2U2ZjBlMTMyZWY0ODVlNmJiZWZkMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fGW4DzybG9ugj06yh-LjiW51-PYvG0fxU-EGCU-W4pU)


I seem to have this exact same problem here, I do not seem to understand how to do the fix you suggested on my end. 

<img width="1128" alt="image" src="https://github.com/user-attachments/assets/b748b270-e046-4c9d-9a32-e2ccc29ddc83">

**Comment by mostafamt** [comment]
@lordvins226 thank you very much, it works for me. you save my time.

**Comment by Hychin123** [comment]
![Screenshot 2024-12-20 123551](https://github.com/user-attachments/assets/72aa1d31-3ff2-46bc-9a61-4effccc10a87)

i got the some problem and try to fix but it not work.

how to fix this problem ?

**Comment by Ossowitz** [comment]
[lordvins226](https://github.com/lordvins226), hello! Thank you very much for providing a workaround! :heartbeat:

**Comment by lordvins226** [comment]
> ![Screenshot 2024-12-20 123551](https://private-user-images.githubusercontent.com/128031766/397626923-72aa1d31-3ff2-46bc-9a61-4effccc10a87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0MTA5MjksIm5iZiI6MTczNTQxMDYyOSwicGF0aCI6Ii8xMjgwMzE3NjYvMzk3NjI2OTIzLTcyYWExZDMxLTNmZjItNDZiYy05YTYxLTRlZmZjY2MxMGE4Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyOFQxODMwMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTNhNjEzZjE4YzdiYjVhZTc0NmVhMGJmMDBhYzI4MmJkMzA4NjhhM2JkZjM4ZjNhYmViN2E1MTFkYjRiN2Y0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vgamGinxl_zhGWe_9qbFrwKH_biEM2NZ3wPQvc00Eq4)
> 
> i got the some problem and try to fix but it not work.
> 
> how to fix this problem ?

correct command: `npx nx g @nxrocks/nx-spring-boot:project ecom-backend --directory apps/ecom-backend 
`

**Comment by tinesoft** [comment]
Sorry for the long overdue.... 

Supports for Nx v20+ has officially landed with latest versions of the plugin.
