### ISSUE TITLE
[Bug] Can't create new flutter project with the latest version of Nx

### ISSUE THREAD

**Issue by lordvins226** [tinesoft/nxrocks#239]
### Plugin Name

@nxrocks/nx-flutter

### Nx Report

NX   Report complete - copy this into the issue template

Node           : 18.19.0
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 9.12.3

nx (global)        : 20.0.1
nx                 : 20.0.1
@nx/js             : 20.0.1
@nx/jest           : 20.0.1
@nx/eslint         : 20.0.1
@nx/workspace      : 20.0.1
@nx/eslint-plugin  : 20.0.1
@nx/react          : 20.0.1
@nx/vite           : 20.0.1
@nx/web            : 20.0.1
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/eslint/plugin
@nx/jest/plugin
@nxrocks/nx-flutter
---------------------------------------
Community plugins:
@nxrocks/nx-flutter : 9.3.1

### Expected Behaviour

Create a project using `nx g @nxrocks/nx-flutter:project libs/ui/mobile/ui-aton`

### Actual Behaviour

nx g @nxrocks/nx-flutter:project libs/ui/mobile/ui-atom --verbose

 NX  Generating @nxrocks/nx-flutter:project

✔ What package name would you like to use? · com.example
✔ What is the project about? ·
✔ Which type of Flutter project would you like to create? · package
✔ Are you using Flutter Version Manager (fvm)? (y/N) · false

 NX   Cannot read properties of undefined (reading 'replace')

TypeError: Cannot read properties of undefined (reading 'replace')
    at removeWindowsDriveLetter (/Users/kevin/workspace/lo-zone/fleet/node_modules/.pnpm/nx@20.0.1_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_xohq3s3fpuf37pev4277fvs2cy/node_modules/nx/src/utils/path.js:9:27)
    at normalizePath (/Users/kevin/workspace/lo-zone/fleet/node_modules/.pnpm/nx@20.0.1_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_xohq3s3fpuf37pev4277fvs2cy/node_modules/nx/src/utils/path.js:16:12)
    at determineProjectNameAndRootOptions (/Users/kevin/workspace/lo-zone/fleet/node_modules/.pnpm/@nx+devkit@20.0.1_nx@20.0.1_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@s_5z4ls3oflnd425gu5fiyfpadgy/node_modules/@nx/devkit/src/generators/project-name-and-root-utils.js:10:58)
    at normalizeOptions (/Users/kevin/workspace/lo-zone/fleet/node_modules/.pnpm/@nxrocks+nx-flutter@9.3.1_@nx+devkit@20.0.1_nx@20.0.1_@swc-node+register@1.9.2_@swc+core@1.5._4wqyc6bjq3vtj7l675kpysxmsm/node_modules/@nxrocks/nx-flutter/src/generators/project/lib/normalize-options.js:6:143)
    at projectGenerator (/Users/kevin/workspace/lo-zone/fleet/node_modules/.pnpm/@nxrocks+nx-flutter@9.3.1_@nx+devkit@20.0.1_nx@20.0.1_@swc-node+register@1.9.2_@swc+core@1.5._4wqyc6bjq3vtj7l675kpysxmsm/node_modules/@nxrocks/nx-flutter/src/generators/project/generator.js:9:64)
    at /Users/kevin/workspace/lo-zone/fleet/node_modules/.pnpm/nx@20.0.1_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_xohq3s3fpuf37pev4277fvs2cy/node_modules/nx/src/command-line/generate/generate.js:238:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleErrors (/Users/kevin/workspace/lo-zone/fleet/node_modules/.pnpm/nx@20.0.1_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_xohq3s3fpuf37pev4277fvs2cy/node_modules/nx/src/utils/handle-errors.js:9:24)
    at async Object.handler (/Users/kevin/workspace/lo-zone/fleet/node_modules/.pnpm/nx@20.0.1_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpers@0.5.13__@swc+types@0.1.12_ty_xohq3s3fpuf37pev4277fvs2cy/node_modules/nx/src/command-line/generate/command-object.js:14:22)

### Steps to reproduce the behaviour

1. Create new nx workspace with "none" preset
2. Install @nxrocks/nx-flutter
3. Create a new flutter project

**Comment by tinesoft** [comment]
Hi @lordvins226 

Thanks for using the plugin and for reporting this.

The `--directory` must indeed be explicit since NX 20.  


I will update the docs soon.

**Comment by Pertempto** [comment]
This also impacts the `npx create-nx-flutter@latest` command
