### ISSUE TITLE
[Bug] getProjectGraph renamed in nx devkit 12.6.x breaks builds

### ISSUE THREAD

**Issue by liamhilliard** [tinesoft/nxrocks#72]
nx-spring-boot: ^2.1.0
nx: 12.6.2

Hi,

I created a new workspace with NX 12.6.2 (latest) and then used nx-spring-boot to try and build the project, but get the following error:

```
$> nx buildJar gb-server
[nx-spring-boot]: Looking Spring Boot related projects inside the workspace...
[nx-spring-boot]: Adding dependencies for project 'gb-server'...
/home/liam/dev/guidebook/node_modules/@nxrocks/nx-spring-boot/src/project-graph.js:48
    return builder.getProjectGraph();
                   ^

TypeError: builder.getProjectGraph is not a function
    at Object.processProjectGraph (/home/liam/dev/guidebook/node_modules/@nxrocks/nx-spring-boot/src/project-graph.js:48:20)
    at /home/liam/dev/guidebook/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:134:23
    at Array.reduce (<anonymous>)
    at updateProjectGraphWithPlugins (/home/liam/dev/guidebook/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:130:20)
    at buildProjectGraph (/home/liam/dev/guidebook/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:107:15)
    at createProjectGraph (/home/liam/dev/guidebook/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:71:26)
    at Object.<anonymous> (/home/liam/dev/guidebook/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:40:16)
    at Generator.next (<anonymous>)
    at /home/liam/dev/guidebook/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/home/liam/dev/guidebook/node_modules/tslib/tslib.js:113:16)
    at Object.createProjectGraphAsync (/home/liam/dev/guidebook/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:39:20)
    at Object.<anonymous> (/home/liam/dev/guidebook/node_modules/@nrwl/workspace/src/command-line/run-one.js:19:52)
    at Generator.next (<anonymous>)
    at fulfilled (/home/liam/dev/guidebook/node_modules/tslib/tslib.js:114:62)
```

It appears nx changed the API for ProjectGraphBuilder in the latest version. You can see the 12.5.x version [here](https://github.com/nrwl/nx/blob/12.5.x/packages/devkit/src/project-graph/utils.ts) with `getProjectGraph`, which was then changed to `getUpdatedProjectGraph` in v12.6.x [here](https://github.com/nrwl/nx/blob/12.6.x/packages/devkit/src/project-graph/project-graph-builder.ts).

I will downgrade to nx 12.5.x to resolve this for now. Apologies for not trying to fix this in a PR, I'm just not sure if this should be fixed with a version label in the package.json or a change to the code.

Thanks for your work on this. It's seriously cool to have Spring integrated with nx!

**Comment by tinesoft** [comment]
Hi @liamhilliard 

Thanks for using the plugin, and for bringing that issue to me.

I'll have a look asap and provide a fix.

Stay tuned!

**Comment by AgentEnder** [comment]
@tinesoft Here is what the fix in nx-dotnet looked like for the same issue. https://github.com/nx-dotnet/nx-dotnet/commit/2e56afc9b46e11ad1fb1ef5ea7767e1923fac0a0#diff-73afab7c3c81f25ec5c6d4f68d26d30fa1fa07ad3671251a93f626731c3d5129

**Comment by oguera** [comment]
Hey @tinesoft,
thanks for the quick fix. Would it be possible that you release a patch release for the npm package? The issue is fixed on develop and the docs are adjusted but there is "still" the old package in npm. If there is a schedule for releases i can easily downgrade nx.

Thanks :)

**Comment by tinesoft** [comment]
Hi @oguera 

A release is coming up very soon (hopefully today or tomorrow) .

I will be  a "major" and not simply a patch release, as it requires an update to Nx v.12.6.x at least (in fact, the bug was due to a breaking change in Nx's DevKit Project Graph API, introduced since v12.6.0).

I have shipped a bunch of nice feats and fixes as well 😇.


You' be notified here as soon as the release is published.

So watch your inbox 📥!
