### ISSUE TITLE
when monorepo library dependency added to application's pom file, it throws error

### ISSUE THREAD

**Issue by jyotibhangale** [tinesoft/nxrocks#84]
### Plugin Name

@nxrocks/nx-quarkus

### Plugin Version

v.2.0.0

### Nx Version

13.3.0

### Expected Behaviour

show dependency graph between library and apps without any error.

### Actual Behaviour

I have a java-api-lib in mono-repo under libs/api, I am adding maven dependency for it in my application's pom file which is under apps/services/kogito-validator. 

When I run nx dep-graph, it throws following error:

[nx-quarkus]: Adding dependencies for project 'services-kogito-validator'...
Error: Source project services-kogito-validator does not have a file: apps\services\kogito-validator\pom.xml
    at ProjectGraphBuilder.addExplicitDependency (\node_modules\@nxrocks\nx-quarkus\node_modules\@nrwl\devkit\src\project-graph\project-graph-builder.js:78:19)
    at \node_modules\@nxrocks\nx-quarkus\src\project-graph.js:53:21
    at Array.forEach (<anonymous>)
    at addDependenciesForProject (\node_modules\@nxrocks\nx-quarkus\src\project-graph.js:50:30)
    at \node_modules\@nxrocks\nx-quarkus\src\project-graph.js:64:9
    at Array.forEach (<anonymous>)
    at Object.processProjectGraph (\node_modules\@nxrocks\nx-quarkus\src\project-graph.js:63:40)
    at \node_modules\@nrwl\workspace\src\core\project-graph\build-project-graph.js:201:33
    at Array.reduce (<anonymous>)
    at updateProjectGraphWithPlugins (\node_modules\@nrwl\workspace\src\core\project-graph\build-project-graph.js:192:46)
    at \node_modules\@nrwl\workspace\src\core\project-graph\build-project-graph.js:84:19
    at Generator.next (<anonymous>)
    at fulfilled (\node_modules\tslib\tslib.js:114:62)

### Steps to reproduce the behaviour

1. create library using following command:
  nx g @nxrocks/nx-quarkus:project java-api --projectType library --buildSystem MAVEN --groupId com.test.quarkus --artifactId java-api --directory api-sec

 nx g @nxrocks/nx-quarkus:project api-server --projectType application --buildSystem MAVEN --groupId com.test.quarkus --artifactId api-server --directory services

2. open services/api-server/pom.xml and add dependency for java-api library.
3. run nx dep-graph
$ nx dep-graph
[nx-quarkus]: Looking Quarkus related projects inside the workspace...
[nx-quarkus]: Adding dependencies for project 'api-sec-java-api'...
[nx-quarkus]: Adding dependencies for project 'services-api-server'...
Error: Source project services-api-server does not have a file: apps\services\api-server\pom.xml
    at ProjectGraphBuilder.addExplicitDependency (C:\Users\test\quarkus-workspace\quarkus-test\node_modules\@nrwl\devkit\src\project-graph\project-graph-builder.js:78:19)
    at C:\Users\test\quarkus-workspace\quarkus-test\node_modules\@nxrocks\nx-quarkus\src\project-graph.js:53:21
    at Array.forEach (<anonymous>)
    at addDependenciesForProject (C:\Users\test\quarkus-workspace\quarkus-test\node_modules\@nxrocks\nx-quarkus\src\project-graph.js:50:30)
    at C:\Users\test\quarkus-workspace\quarkus-test\node_modules\@nxrocks\nx-quarkus\src\project-graph.js:64:9
    at Array.forEach (<anonymous>)
    at Object.processProjectGraph (C:\Users\test\quarkus-workspace\quarkus-test\node_modules\@nxrocks\nx-quarkus\src\project-graph.js:63:40)
    at C:\Users\test\quarkus-workspace\quarkus-test\node_modules\@nrwl\workspace\src\core\project-graph\build-project-graph.js:201:33
    at Array.reduce (<anonymous>)
    at updateProjectGraphWithPlugins (C:\Users\test\quarkus-workspace\quarkus-test\node_modules\@nrwl\workspace\src\core\project-graph\build-project-graph.js:192:46)
    at C:\Users\test\quarkus-workspace\quarkus-test\node_modules\@nrwl\workspace\src\core\project-graph\build-project-graph.js:84:19
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\test\quarkus-workspace\quarkus-test\node_modules\tslib\tslib.js:114:62)
Failed to process the project graph with "@nxrocks/nx-quarkus". This will error in the future!
[nx-quarkus]: Looking Quarkus related projects inside the workspace...
[nx-quarkus]: Adding dependencies for project 'api-sec-java-api'...
[nx-quarkus]: Adding dependencies for project 'services-api-server'...
Error: Source project services-api-server does not have a file: apps\services\api-server\pom.xml
    at ProjectGraphBuilder.addExplicitDependency (C:\Users\test\quarkus-workspace\quarkus-test\node_modules\@nrwl\devkit\src\project-graph\project-graph-builder.js:78:19)
    at C:\Users\test\quarkus-workspace\quarkus-test\node_modules\@nxrocks\nx-quarkus\src\project-graph.js:53:21
    at Array.forEach (<anonymous>)

**Comment by tinesoft** [comment]
Hi @jyotibhangale 

For using the plugin and for reporting the issue.
I will have a look asap.

**Comment by jyotibhangale** [comment]
Hi, 
Right, we don't have application and libraries directly  under app/, lib/. We have subfolders within it and apps and libs goes under it.
So I was doing little more debugging on this and found that it's just path separator causing problem. In my case I am running it on windows: and path for pom is this apps\services\kogito-validator\pom.xml but plugin actually verifies it with path 
apps/services/kogito-validator/pom.xml
 ProjectGraphBuilder.ProjectGraph have FileData and within it files have / as path separator. I haven't reached to why FileData have / as path Seperator.

**Comment by jyotibhangale** [comment]
Hi @tinesoft ,

I see that with latest code changes, I don't see this particular issue, do I need to get latest plugin build in order to fix it for me?

**Comment by tinesoft** [comment]
Seems fixed by https://github.com/tinesoft/nxrocks/releases/tag/nx-spring-boot%2Fv4.0.0
